### ISSUE TITLE
Enhancement: Userscript support for a button "upload to emp" within stash

### ISSUE THREAD

**Issue by preshow6237** [bdbenim/stash-empornium#58]
Title basically.

Add a button on a stash scene's panel . The edit tab makes most sense, as the workflow would be to scrape the scene, edit all the tags/metainfo etc, then upload. The button would basically open an empornium upload.php tab, and pre-populate that scenes id number into the "stash ID" field provided by the script. It could automatically activate the "fill form" button provided by the script. You'd have to assume that the user is already authenticated/logged in, so  maybe/maybe not handle that "error", and you'd need to make .sx or .is domain configurable in the config I guess.

**Workflow becomes:**
- Edit meta data in stash until you're happy with it
- Click "upload to emp" button
- New tab opens (ideally without even changing focus to it), and starts working on all the jobs.
- User can keep working on the next scene or whatever, or upload a new one. These jobs can happen asynchronously I presume (I haven't actually tested).
- At some point the user can come back to the emp tab(s) and review and click upload.

This enhancement would be improved by caching of image urls (which you've implemented but not released I believe), caching of the .torrent generation job being complete, etc, etc. So even if an upload tab is forgotten/closed by the user at some point they can simply click the button on the scene again and have it be "instantly" ready.

**Potential issue:**
If the user processes like 10 scenes at a time, it might be painful to associate the correct .torrent with each tab. It would be great if you could inject this as a part of the script. It's entirely possible to just make the .torrent in client-side js (see anthelion's upload.php, the js is all there). This should be it's own issue (lol). And this approach probably isn't great, because then caching the resulting .torrent becomes problematic should you need to re-run the script. 

### Tasks
- [x] #128
- [x] #129
- [x] #130
- [ ] Reliably know when to clear jobs from the list

**Comment by bdbenim** [comment]
I've been thinking about this for a while, because I think it's going to be more difficult than it sounds for two reasons:
1. I'm a much better backend than frontend dev, and this is going to be frontend-heavy
2. Interacting with empornium's upload form from within stash is going to take some hacking because it's the exact kind of thing that modern browsers try to prevent for security reasons

I think I have the answer to these however:
1. Suck it up and learn frontend dev
2. Rather than try to find a way to open `upload.php` with the data preloaded into the upload form, simply start the job on the backend and provide a convenient interface for retrieving that job from the frontend

More specifically, here's how I envision point 2 working:
1. Using a second userscript, add a button to the stash interface as described by @preshow6237 above
2. When the user presses this button, start a job on the backend to prepare an upload for that scene, and (optionally?) open `upload.php`
3. Using the existing userscript, add a menu (probably just a dropdown box or something) to retrieve the job that was started on the backend
4. If the user selects a job from the menu above, then wait for it to complete if it has not already, and then populate the upload form in the usual way
5. Clear jobs from the menu once uploaded to empornium

**Work that this will require:**
- [ ] Abstract upload generation away from the `/fill` endpoint of the backend so that it can be prepared and retrieved asynchronously
- [ ] Create a second userscript that will add a button to stash and trigger the backend job
- [ ] Update the primary userscript to retrieve jobs from the backend
- [ ] Reliably know when to clear jobs from the list
  - Possibly as soon as they're retrieved via `upload.php`
  - Alternatively, once the upload button is pressed, but this will likely only work if the user presses the modified upload button
  - As a backup, it should probably be possible to clear jobs manually from the backend's web ui

**Advantages:**
De-linking generation jobs from the `/fill` endpoint will pave the way for other features that provide control over jobs, such as:
- Displaying job history and progress in the web ui
- Starting or stopping jobs from the ui

**Comment by bunkmate5127** [comment]
To make matters more complicated...

Be aware that a single scene can have multiple associated files, so the job creation / sending process / button / ui, would need to be cognisant of this in a similar way that upload.php's userscript currently is.

I don't know much about frontend dev either, I can bumble my way through backend dev—but really I'm an embedded dev/EE... real monkey stuff using C/C++ with IC datasheets for reference. I'm somewhat surprised that there's not a mechanism to open a tab and pre-populate it with data with the violent-monkey/tampermonkey etc add-ons. The population of data functionality obviously exists, as the script is already capable of that—so really it's the inability to spawn a new tab, or redirect a tab to a new url, to populate the data that's lacking. 

I had basically envisaged the process being:
1. button links spawns upload.php and prepopulates the stash scene id into the field/script memory, the "start" function of the script is automatically activated. 
2. script runs as normal

But I'll be the first to admit that I have no knowledge of the limitations of tamper/violent monkey, or what locks browsers place around this stuff (it's eerily similar to "pop-ups" which would be blocked, but I don't see how it's fundamentally that different to a simple html href link—the devil is no doubt in the details).

Regardless, if you think there's extra utility offered by implementing a job's queue and separation from the upload.php entirely then that's probably worth pursuing. Other than my own perceived ease of this solution, there's no other benefit to this approach, it was intended as a rough-and-ready "easy-to-implement" user time saver/ux improvement. But from what you've written I think my assumptions are well off-base.
